### ISSUE TITLE
Webview page to run Code Ready Containers

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1235]
This page which create a webview interface providing the feature for the user to Run Code Ready Containers.

When the user clicks on `Add OpenShift Cluster` icon on the title panel, the webview is loaded. 
Once the view is active, it shows 2 options to Add an OpenShift Cluster.

1. Local Installation
- Install on Laptop: Red Hat CodeReady Containers.
- Action: Load the CRC view to configure parameters and start crc.

2. Hybrid Installation
- Install, register, and manage OpenShift 4 clusters.
- Action: Redirects to the official document page at https://cloud.redhat.com/openshift/install

These will be shown as cards and respective actions will be enabled on the card button

After box 1 is selected CRC Install page is activated. The page will provide steps to:
1. Select CRC version grouped by OpenShift version
2. Download CRC binary and provide the full path of the crc executable
3. Specify the pull secret
4. Set optional configuration like memory and cores
5. Start Cluster
6. Open Console Url

# Features needed for CRC integration in VSCode #
- [x] Add progress bar for crc command completion

- [x] Run `crc setup` and then `crc start` command as child process

- [x] Show console url once the cluster is up and running

- [x] Showcase command output stream in UI

- [x] Download link to the specific version of crc selected (see beginning of discussion in #1546).

**Comment by dgolovin** [comment]
Released on 10/4/20.
