### ISSUE TITLE
Replace used oc commands with odo commands

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1355]
Extension should always use `odo` commands in place of `oc`. If there is no odo command corresponding to oc command used in extension, it should be implemented on oc side or replaced with JavaScript k8s client call if possible.

Currently extension is using oc:
- [x] #1356 To get list of component's ports
- [ ] To get service template name before showing
- [ ] To distinguish 3.x and 4.x clusters
- [ ] To find out OpenShift console url
- [ ] To find out OpenShift cluster url
- [ ] #1419 To wait for project to be deleted
- [ ] To wait for storage to be deleted
- [ ] To wait for service to be deleted
- [ ] To change current context
- [ ] To create new resources from manifest files
- [ ] To get tags from imageStream resource (to identify Java and Node.js components in `OpenShift: Debug` command)

**Comment by sbouchet** [comment]
@dgolovin, here is how we implement those actions for our implementation for IntelliJ:

> * To get list of component's ports --> K8s client
> * To get service template name before showing --> `odo catalog list services -o json`
> * To distinguish 3.x and 4.x clusters --> K8s client 
> * To find out OpenShift console URL --> K8s client
> * To find out OpenShift cluster URL --> K8s client
> * To wait for project to be deleted --> odo delete but wait feature not implemented 
> * To wait for storage to be deleted --> odo delete but wait feature not implemented
> * To wait for service to be deleted --> odo delete but wait feature not implemented
> * To change current context --> pure Java by parsing/writing kubeconfig file
> * To create new resources from manifest files --> not implemented
> * To get tags from imageStream resource (to identify Java and Node.js components in `OpenShift: Debug` command) --> K8s client

**Comment by dgolovin** [comment]
This is not possible for now because we using oc to work with resources in k8s cluster view.
