### ISSUE TITLE
Add/Remove/Update Registry commands for Component Types View and Command Pallete

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2005]
There should be a way to configure registries using vscode UI through:
1. Command palette
2. Navigation command in View title
3. Context menu on Registry object instance in view

Functionalities:

- [ ] add a new devfile registry
- [ ] remove an existing devfile registry
- [ ] edit an existing devfile registry

**Comment by mohitsuman** [comment]
Adding scenario from jboss tools
See also https://issues.redhat.com/browse/JBIDE-27610
