### ISSUE TITLE
Add Helm Charts UI in extension

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2132]
### Goal

Some of the features the extension can support:
- [ ] Webview to show the charts on the same lines of registry viewer
- [ ] Browse the Helm catalog to install and view charts available using Help API
- [ ] Install helm charts for the applications
