### ISSUE TITLE
Allow to run all OpenShift commands from palette

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#269]
Now only part of commands are available for use from command palette, because most of the commands require context OpenShift object, which comes from selected node in OpenShift App Explorer view. to fix this every command should as user for context if called form command palette.
- [x] #236 Add 'OpenShift: Delete Storage' command to command palette
- [x] #235 Add 'OpenShift: Delete Service' command to command palette
- [x] #234 Add 'OpenShift: Delete Component' command to command palette
- [x] #233 Add 'OpenShift: Delete Application' command to command palette
- [x] #232 Add 'OpenShift: Delete Project' command to command palette
- [x] #454 Add 'OpenShift: New Project' command to command palette
- [x] #230 Add 'OpenShift: New Application' command to command palette
- [x] #317 Add 'OpenShift: New Component' command to command palette
- [x] #318 Add 'OpenShift: New Service' command to command palette
- [x] #319 Add 'OpenShift:  Create Storage' command to command palette
- [x] #320 Add 'OpenShift:  Create URL' command to command palette
- [x] #321 Add 'OpenShift:  Create Service' command to command palette
- [x] #322 Add 'OpenShift:  Watch' command to command palette
- [x] #323 Add 'OpenShift:  Push' command to command palette
- [x] #324 Add 'OpenShift:  Show Log' command to command palette
- [x] #325 Add 'OpenShift:  Follow Log' command to command palette
- [x] #326 Add 'OpenShift:  Open in Browser' command to command palette
- [x] #327 Add 'OpenShift:  Describe Application' command to command palette
- [x] #328 Add 'OpenShift:  Describe Component' command to command palette
- [x] #348 Add 'OpenShift: Open Console for Current Cluster' command to command palette

**Comment by dgolovin** [comment]
@sudhirverma: All the PRs have the same problem. The problem is code duplication or in short CD. For component related operations CD is about getting target component. For creating a service or a component it is about getting target application.
