### ISSUE TITLE
[EPIC] Devfile registry search bar improvements and bug fix

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2960]
**Bug**:

Currently the Devfile Registry view search bar refreshes as soon as we click back on it. For example, user clicks on search and types Django. The search results are updated, but as soon you click on search bar, it removes the text and thus the results are again updated to default search showing all the devfiles.

**Fix**:

- [ ] The search bar element should not be removed as soon user clicks on it again. There should be a clear (x icon) at the end of the search bar to remove the text completely.

For reference: 
<img width="715" alt="Screenshot 2023-06-12 at 5 22 20 PM" src="https://github.com/redhat-developer/vscode-openshift-tools/assets/3133356/f95d8b83-cc54-4067-b78b-9c5dcc22c355">

- [ ]  Reduce the length of the search box element. 

- [ ] Add information around the of devfiles present. This should be dynamic based on the search result length. Show this beside the search bar. 

Example text: `Showing 25 devfiles`

For reference:
<img width="1315" alt="Screenshot 2023-06-12 at 5 24 49 PM" src="https://github.com/redhat-developer/vscode-openshift-tools/assets/3133356/9a51d53e-a55f-49c6-be49-557a03d2115c">
