### ISSUE TITLE
Use odo's machine readable output option `-o` to get information about odo objects

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#502]
- [x] #721 Use `odo project list -o json` to get list of projects
- [x] #722 Use `odo list -o json` to get list of components
- [x] #723 Use `odo catalog list components -o json` to get list of available component types and versions
- [x] #724 Use `odo catalog list services -o json` to get list of available service templates and plans
- [x] #725 Use `odo storage list -o json` to get list of storage objects in mounted for component
- [x] #726 Use `odo service list -o json` to get list of provisioned service instances
- [x] #727 Use `odo describe <compName> -o json` to get exposed ports/protocols list
- [x] #728 Use `odo url list -o json` to fetch list of URLs for component
- [x] #740 Use `odo url list -o json` to return empty list of no URL configured

**Comment by jorgemoralespou** [comment]
Related odo issues:
- https://github.com/redhat-developer/odo/issues/784
- https://github.com/redhat-developer/odo/issues/1062
