### ISSUE TITLE
Add validation for duplicate item names

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#549]
Since we now have duplicate name validation for openshift components, we should get it for other items as well. Trying to create items with the same name results the odo command failing with a generic error message, which is not very nice.

- [x] #566  Validation for creating New Storage 
- [x] #491  Added validation for New Application to check there are no application with the same available 
- [x] #490 Added validation for New Storage to check there are no resources with the same name in cluster available 
- [x] #489 Added validation for New Services to check there are no resources with the same name in cluster available 
- [x] #484  Added validation for New Project to check there are no resources with the same name in cluster available
