### ISSUE TITLE
odo 0.0.19 migration

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#621]
- [x] #501 Improve odo error handling
- [x] #622 Load Application from  odo configuration file in ~/.odo/odo-config
- [x] #626 Update odo download information for new v0.0.19 release
