### ISSUE TITLE
Component commands need choices filtered by their state

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#970]
Each component state has different set of available commands. Calling these commands from the palette will allow the user to choose components that should not be available for the given command.

For example, `not pushed` command can be chosen as target for the `New URL` command, which leads to an inevitable error.

- [x]  #1076 'Create Storage' command should allow to pick only deployed components
- [x]  #1078 'Describe Component' command should show components in 'pushed' or 'no context' state
- [x]  #1079 'Show/Follow Component's Log' commands should show only components in 'pushed' state
- [x]  #1080 'Link/Unlink' commands and services should show only components in 'pushed' state
- [x]  #1081 'Open in Browser' commands should show only components in 'pushed' state
- [x]  #1082 'Watch/Undeploy` commands should show only components in 'pushed' state
- [x]  #1096 'Push' commands should show components in 'pushed' and 'not-pushed' states

**Comment by jeffmaury** [comment]
Except that you should be able to create an URL for a non pushed component !!!!

**Comment by jrichter1** [comment]
@jeffmaury care to create an issue for that? :)

But for other commands, things like linking other components should only really work when deployed, right?

**Comment by dgolovin** [comment]
@jrichter1 noticed that for linking, but not for other commands :( good catch!
